# Generated by Django 2.0.4 on 2018-04-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_auto_20180428_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='exp_email_sent',
            field=models.BooleanField(default=False, help_text='shows if expiration email was sent on this auction'),
        ),
    ]
